<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>b1.R</title>
<link rel="stylesheet" type="text/css" href="highlight.css"/>
</head>
<body class="hl">
<pre class="hl"><span class="slc"># Goals: A first look at R objects - vectors, lists, matrices, data frames.</span>

<span class="slc"># To make vectors &quot;x&quot; &quot;y&quot; &quot;year&quot; and &quot;names&quot;</span>
x <span class="sym">&lt;-</span> c<span class="sym">(</span><span class="num">2</span><span class="sym">,</span><span class="num">3</span><span class="sym">,</span><span class="num">7</span><span class="sym">,</span><span class="num">9</span><span class="sym">)</span>
y <span class="sym">&lt;-</span> c<span class="sym">(</span><span class="num">9</span><span class="sym">,</span><span class="num">7</span><span class="sym">,</span><span class="num">3</span><span class="sym">,</span><span class="num">2</span><span class="sym">)</span>
year <span class="sym">&lt;-</span> <span class="num">1990</span><span class="sym">:</span><span class="num">1993</span>
names <span class="sym">&lt;-</span> c<span class="sym">(</span><span class="str">&quot;payal&quot;</span><span class="sym">,</span> <span class="str">&quot;shraddha&quot;</span><span class="sym">,</span> <span class="str">&quot;kritika&quot;</span><span class="sym">,</span> <span class="str">&quot;itida&quot;</span><span class="sym">)</span>
<span class="slc"># Accessing the 1st and last elements of y --</span>
y<span class="sym">[</span><span class="num">1</span><span class="sym">]</span>
y<span class="sym">[</span>length<span class="sym">(</span>y<span class="sym">)]</span>

<span class="slc"># To make a list &quot;person&quot; --</span>
person <span class="sym">&lt;-</span> list<span class="sym">(</span>name<span class="sym">=</span><span class="str">&quot;payal&quot;</span><span class="sym">,</span> x<span class="sym">=</span><span class="num">2</span><span class="sym">,</span> y<span class="sym">=</span><span class="num">9</span><span class="sym">,</span> year<span class="sym">=</span><span class="num">1990</span><span class="sym">)</span>
person
<span class="slc"># Accessing things inside a list --</span>
person$name
person$x

<span class="slc"># To make a matrix, pasting together the columns &quot;year&quot; &quot;x&quot; and &quot;y&quot;</span>
<span class="slc"># The verb cbind() stands for &quot;column bind&quot;</span>
cbind<span class="sym">(</span>year<span class="sym">,</span> x<span class="sym">,</span> y<span class="sym">)</span>

<span class="slc"># To make a &quot;data frame&quot;, which is a list of vectors of the same length --</span>
D <span class="sym">&lt;-</span> data.frame<span class="sym">(</span>names<span class="sym">,</span> year<span class="sym">,</span> x<span class="sym">,</span> y<span class="sym">)</span>
nrow<span class="sym">(</span>D<span class="sym">)</span>
<span class="slc"># Accessing one of these vectors</span>
D$names
<span class="slc"># Accessing the last element of this vector</span>
D$names<span class="sym">[</span>nrow<span class="sym">(</span>D<span class="sym">)]</span>
<span class="slc"># Or equally,</span>
D$names<span class="sym">[</span>length<span class="sym">(</span>D$names<span class="sym">)]</span>
</pre>
</body>
</html>
<!--HTML generated by highlight 2.4-1, http://www.andre-simon.de/-->
